### ISSUE TITLE
TypeError: pageRoute is not a function

### ISSUE THREAD

**Issue by MichaelChen666** [honghuangdc/router-page#3]
目前对大前端的模块这块不太熟，不过发现一些问题，若是本人使用不当，请见谅。

当 package.json type字段默认（即为 commonjs）时，没有任何问题，ts 和 vite 构建都是 ok 的。

当 package.json type 设置为 `module` （目前最佳实践） 时，ts 解析没有问题，但是 vite 构建失败。

![image](https://github.com/soybeanjs/vite-plugin-vue-page-route/assets/42194010/3a87902a-d9e6-4958-ae81-b3118591d16f)

![image](https://github.com/soybeanjs/vite-plugin-vue-page-route/assets/42194010/a7d9ebd1-27f1-4750-a29e-17cf41e32fb4)

其它插件都没有问题， 比如 `vite-plugin-progress`。对比下二者包的 package.json。

vite-plugin-progress/package.json:

```json
{
  "name": "vite-plugin-progress",
  "version": "0.0.7",
  "description": "A progress bar plugin for Vite.",
  "main": "dist/index.js",
  "module": "dist/index.mjs",
  "types": "dist/index.d.ts",
  "exports": {
    ".": {
      "require": "./dist/index.js",
      "import": "./dist/index.mjs",
      "types": "./dist/index.d.ts"
    }
  }
}
```

@soybeanjs/vite-plugin-vue-page-route/package.json:

```json
{
  "main": "dist/index.js",
  "module": "dist/index.mjs",
  "types": "dist/index.d.ts",
  "files": [
    "dist"
  ]
}
```

ts 解析没有问题，但是当 vite 构建时，package.json type 为 module 时，会按照 es 模块来解析依赖和type信息。

如上所述，soybeanjs/vite-plugin-vue-page-route 并不支持 package.json type=module 模式。

**Comment by honghuangdc** [comment]
目前是没有提供mjs和cjs，我晚上有空实现一下

**Comment by MichaelChen666** [comment]
> 目前是没有提供mjs和cjs，我晚上有空实现一下

多谢大佬。

**Comment by honghuangdc** [comment]
新版本已支持ESM方式
